name: Sphinx documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Set up R 3.6
      uses: r-lib/actions/setup-r@master
      with:
        r-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pandoc
        python -m pip install --upgrade pip
        pip install -r doc/requirements.txt
        python setup.py install --force
        sudo Rscript ./install_r_packages.r BiocManager dbplyr dplyr ggplot2 hexbin lazyeval RSQLite tidyr viridis
        sudo Rscript -e 'BiocManager::install("Biobase")'
    - name: Build HTML doc
      run: |
        export LD_LIBRARY_PATH=$(python -m rpy2.situation LD_LIBRARY_PATH):${LD_LIBRARY_PATH}
        python -m rpy2.situation
        cd doc
        make notebooks
        make html
